/**
 * @fileoverview 기술 스택 로고 URL 매핑.
 *
 * Figma 디자인 시스템의 68개 공식 기술 스택 칩에 사용하는 로고 이미지를 관리한다.
 * 로고는 public/icons/tech/ 폴더의 SVG 파일을 사용하거나,
 * 추후 CDN URL로 교체할 수 있다.
 *
 * 현재는 placeholder로 빈 문자열을 사용하며,
 * 실제 배포 시 로고 SVG를 다운로드하여 `/icons/tech/{name}.svg`에 배치한다.
 */

export const TECH_STACK_NAMES = [
  'Java',
  'Kotlin',
  'JavaScript',
  'TypeScript',
  'Python',
  'Go',
  'C++',
  'C#',
  'Rust',
  'PHP',
  'Ruby',
  'Swift',
  'React',
  'Next.js',
  'Vue.js',
  'Nuxt',
  'Angular',
  'Svelte',
  'Tailwind CSS',
  'Vite',
  'Spring Boot',
  'Node.js',
  'Express',
  'NestJS',
  'FastAPI',
  'Django',
  'Flask',
  'Laravel',
  'Ruby on Rails',
  'ASP.NET Core',
  'Android',
  'iOS',
  'Flutter',
  'React Native',
  'PostgreSQL',
  'MySQL',
  'MariaDB',
  'MongoDB',
  'Redis',
  'SQLite',
  'Oracle',
  'SQL Server',
  'Elasticsearch',
  'DynamoDB',
  'Firebase',
  'Supabase',
  'AWS',
  'GCP',
  'Azure',
  'Docker',
  'Kubernetes',
  'Nginx',
  'Linux',
  'Git',
  'GitHub Actions',
  'Jenkins',
  'Terraform',
  'Kafka',
  'OpenAI',
  'TensorFlow',
  'PyTorch',
  'scikit-learn',
  'Hugging Face',
  'Apache Spark',
  'Figma',
  'Postman',
  'Swagger',
  'Jira',
] as const

export type TechStackName = (typeof TECH_STACK_NAMES)[number]

/**
 * 기술 스택별 로고 URL 매핑.
 * 로컬 SVG 사용 시: `/icons/tech/java.svg` 형태로 교체.
 * 현재는 빈 문자열이면 fallback(이니셜)이 표시된다.
 */
export const TECH_STACK_LOGOS: Record<TechStackName, string> = {
  Java: '/icons/tech/java.svg',
  Kotlin: '/icons/tech/kotlin.svg',
  JavaScript: '/icons/tech/javascript.svg',
  TypeScript: '/icons/tech/typescript.svg',
  Python: '/icons/tech/python.svg',
  Go: '/icons/tech/go.svg',
  'C++': '/icons/tech/cpp.svg',
  'C#': '/icons/tech/csharp.svg',
  Rust: '/icons/tech/rust.svg',
  PHP: '/icons/tech/php.svg',
  Ruby: '/icons/tech/ruby.svg',
  Swift: '/icons/tech/swift.svg',
  React: '/icons/tech/react.svg',
  'Next.js': '/icons/tech/nextjs.svg',
  'Vue.js': '/icons/tech/vuejs.svg',
  Nuxt: '/icons/tech/nuxt.svg',
  Angular: '/icons/tech/angular.svg',
  Svelte: '/icons/tech/svelte.svg',
  'Tailwind CSS': '/icons/tech/tailwindcss.svg',
  Vite: '/icons/tech/vite.svg',
  'Spring Boot': '/icons/tech/springboot.svg',
  'Node.js': '/icons/tech/nodejs.svg',
  Express: '/icons/tech/express.svg',
  NestJS: '/icons/tech/nestjs.png',
  FastAPI: '/icons/tech/fastapi.svg',
  Django: '/icons/tech/django.svg',
  Flask: '/icons/tech/flask.svg',
  Laravel: '/icons/tech/laravel.svg',
  'Ruby on Rails': '/icons/tech/rubyonrails.svg',
  'ASP.NET Core': '/icons/tech/aspnetcore.svg',
  Android: '/icons/tech/android.svg',
  iOS: '/icons/tech/ios.svg',
  Flutter: '/icons/tech/flutter.svg',
  'React Native': '/icons/tech/react.svg',
  PostgreSQL: '/icons/tech/postgresql.svg',
  MySQL: '/icons/tech/mysql.svg',
  MariaDB: '/icons/tech/mariadb.svg',
  MongoDB: '/icons/tech/mongodb.svg',
  Redis: '/icons/tech/redis.svg',
  SQLite: '/icons/tech/sqlite.svg',
  Oracle: '/icons/tech/oracle.svg',
  'SQL Server': '/icons/tech/sqlserver.svg',
  Elasticsearch: '/icons/tech/elasticsearch.svg',
  DynamoDB: '/icons/tech/dynamodb.svg',
  Firebase: '/icons/tech/firebase.svg',
  Supabase: '/icons/tech/supabase.svg',
  AWS: '/icons/tech/aws.svg',
  GCP: '/icons/tech/gcp.svg',
  Azure: '/icons/tech/azure.svg',
  Docker: '/icons/tech/docker.svg',
  Kubernetes: '/icons/tech/kubernetes.svg',
  Nginx: '/icons/tech/nginx.svg',
  Linux: '/icons/tech/linux.svg',
  Git: '/icons/tech/git.svg',
  'GitHub Actions': '/icons/tech/githubactions.svg',
  Jenkins: '/icons/tech/jenkins.svg',
  Terraform: '/icons/tech/terraform.svg',
  Kafka: '/icons/tech/kafka.svg',
  OpenAI: '/icons/tech/openai.svg',
  TensorFlow: '/icons/tech/tensorflow.svg',
  PyTorch: '/icons/tech/pytorch.svg',
  'scikit-learn': '/icons/tech/scikitlearn.svg',
  'Hugging Face': '/icons/tech/huggingface.svg',
  'Apache Spark': '/icons/tech/apachespark.svg',
  Figma: '/icons/tech/figma.svg',
  Postman: '/icons/tech/postman.svg',
  Swagger: '/icons/tech/swagger.svg',
  Jira: '/icons/tech/jira.svg',
}

/**
 * 기술 스택 카테고리 그룹핑
 */
export const TECH_STACK_CATEGORIES = {
  언어: [
    'Java',
    'Kotlin',
    'JavaScript',
    'TypeScript',
    'Python',
    'Go',
    'C++',
    'C#',
    'Rust',
    'PHP',
    'Ruby',
    'Swift',
  ],
  프론트엔드: ['React', 'Next.js', 'Vue.js', 'Nuxt', 'Angular', 'Svelte', 'Tailwind CSS', 'Vite'],
  백엔드: [
    'Spring Boot',
    'Node.js',
    'Express',
    'NestJS',
    'FastAPI',
    'Django',
    'Flask',
    'Laravel',
    'Ruby on Rails',
    'ASP.NET Core',
  ],
  모바일: ['Android', 'iOS', 'Flutter', 'React Native'],
  데이터베이스: [
    'PostgreSQL',
    'MySQL',
    'MariaDB',
    'MongoDB',
    'Redis',
    'SQLite',
    'Oracle',
    'SQL Server',
    'Elasticsearch',
    'DynamoDB',
    'Firebase',
    'Supabase',
  ],
  '인프라·DevOps': [
    'AWS',
    'GCP',
    'Azure',
    'Docker',
    'Kubernetes',
    'Nginx',
    'Linux',
    'Git',
    'GitHub Actions',
    'Jenkins',
    'Terraform',
    'Kafka',
  ],
  'AI·데이터': ['OpenAI', 'TensorFlow', 'PyTorch', 'scikit-learn', 'Hugging Face', 'Apache Spark'],
  '도구·협업': ['Figma', 'Postman', 'Swagger', 'Jira'],
} as const satisfies Record<string, readonly TechStackName[]>
